/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)

{

	// ------------------------------
   // 1. Configuration clock 72 MHz
    // ------------------------------

	RCC_CR |= (1<<16);           // HSE ON
	while(!(RCC_CR & (1<<17)));  // Waiting for HSE to be ready

	FLASH_ACR &= ~0x7;           // Clear wait states
	FLASH_ACR |= 0x2;            // 2 wait states for 72 MHz

	RCC_CFGR |= (1<<16);         // PLLSRC = HSE
	RCC_CFGR &= ~(0xF << 18);    // Clear PLLMUL
    RCC_CFGR |= (7 << 18);       // PLL x9 → 8*9 = 72 MHz

	RCC_CR |= (1<<24);           // PLL ON
	while(!(RCC_CR & (1<<25)));  // Wait for PLL ready

    RCC_CFGR &= ~0x3;            // clear SW
	RCC_CFGR |= 0x2;             // SW = 10 → SYSCLK = PLL
	while(((RCC_CFGR >> 2) & 0x3) != 0x2);  // Wait until SYSCLK = PLL

	// ------------------------------
	// 2.  Enable GPIOA clock, configure PA7 as output, PA0 as input
    // ------------------------------


	RCC_APB2ENR |= RCC_APB2ENR_GPIOAEN;
	GPIOA_CRL &= ~(0xF<<RELAY_PIN_POS * 4);
	GPIOA_CRL |=(0x2<<RELAY_PIN_POS * 4);
	GPIOA_CRL &= ~(0xF);
    GPIOA_CRL |=0x8;


while(1){

    /* Loop forever */
	uint8_t IRSensorState = GPIOA_IDR & 1;
	if(IRSensorState)
		 GPIOA_ODR |= (1<<RELAY_PIN_POS);

	else
		 GPIOA_ODR &= ~(1<<RELAY_PIN_POS);


}
}
